### ISSUE TITLE
UserDirectories#{downloadDir,publicDir} not available on Windows

### ISSUE THREAD

**Issue by SackCastellon** [soc/directories-jvm#10]
I printed all the directories from `new ProjectDirectories.from("com", "Foo Corp", "Bar App")`, `BaseDirectories` and `UserDirectories` on Windows 10 and I got the following:
### ProjectDirectories
```properties
projectPath=Foo Corp/Bar App
tcacheDir=C:\Users\<myName>\AppData\Roaming/Foo Corp/Bar App/data/cache
configDir=C:\Users\<myName>\AppData\Roaming
dataDir=C:\Users\<myName>\AppData\Roaming
tdataLocalDir=C:\Users\<myName>\AppData\Local/Foo Corp/Bar App/data
runtimeDir=null
```

### BaseDirectories
```properties
homeDir=C:\Users\<myName>
dataLocalDir=C:\Users\<myName>\AppData\Local
cacheDir=C:\Users\<myName>\AppData\Local
executableDir=null
```

### UserDirectories
```properties
audioDir=null
fontDir=null
desktopDir=D:\<myName>\Desktop
documentDir=null
downloadDir=null
pictureDir=null
publicDir=null
templateDir=C:\Users\<myName>\AppData\Roaming\Microsoft\Windows\Templates
videoDir=null
```
Nearly none of the `UserDirectories` is detected.

**Note:** The Desktop location is correct, I remapped it to a secondary drive

**Comment by soc** [comment]
Thanks!
I will investigate. Does this problem also appear with version 6?

**Comment by SackCastellon** [comment]
In version 6 I cannot even access the `BaseDirectories` fields because all of them have _default_ visibility

![image](https://user-images.githubusercontent.com/5330355/37704482-33e5e474-2cf9-11e8-8505-b2c915f2a55b.png)

**Comment by soc** [comment]
@SackCastellon Ooops, sorry for the suggestion. I forgot that this issue was fixed so late.

Can you run the following PowerShell commands manually and tell me the results on your system?

```
[Environment]::GetFolderPath([Environment+SpecialFolder]::UserProfile)
[Environment]::GetFolderPath([Environment+SpecialFolder]::Music)
[Environment]::GetFolderPath([Environment+SpecialFolder]::Desktop)
[Environment]::GetFolderPath([Environment+SpecialFolder]::Documents)
[Environment]::GetFolderPath([Environment+SpecialFolder]::Downloads)
[Environment]::GetFolderPath([Environment+SpecialFolder]::Pictures)
[Environment]::GetFolderPath([Environment+SpecialFolder]::Public)
[Environment]::GetFolderPath([Environment+SpecialFolder]::Templates)
[Environment]::GetFolderPath([Environment+SpecialFolder]::Videos)
[Environment]::GetFolderPath([Environment+SpecialFolder]::ApplicationData)
[Environment]::GetFolderPath([Environment+SpecialFolder]::LocalApplicationData)
```

This would help identifying the specific issue at hand! Thanks!

**Comment by SackCastellon** [comment]
![image](https://user-images.githubusercontent.com/5330355/37716830-b59aaf38-2d1f-11e8-881e-491bf13c49d7.png)

**Comment by soc** [comment]
@SackCastellon Thanks for your help!

Could you have a look at https://github.com/soc/directories-jvm/commit/bfd70a334c9d70f832b6f42cf688d917c5dd7353 and try version 9, which I just published?

Thanks!

**Comment by SackCastellon** [comment]
Now it works better:
```properties
audioDir=D:\<myName>\Music
fontDir=null
desktopDir=D:\<myName>\Desktop
documentDir=D:\<myName>\Documents
downloadDir=null
pictureDir=D:\<myName>\Pictures
publicDir=null
templateDir=C:\Users\<myName>\AppData\Roaming\Microsoft\Windows\Templates
videoDir=D:\<myName>\Videos
```
 But I think there should be some way to retrieve the `Downloads` folder location.

**Comment by soc** [comment]
I read the .NET source file of the `SpecialFolder` enum, it seems as if the values for `download` and `public` are somehow missing. :-(

**Comment by soc** [comment]
I filed a bug against .NET in https://github.com/dotnet/corefx/issues/28356.

I'll update the title to reflect that only those two are missing now, and the rest was a bug that was fixed.

**Comment by soc** [comment]
Fixed in version 10. Thanks!
