### ISSUE TITLE
Review change to minimized process spawning

### ISSUE THREAD

**Issue by soc** [soc/directories-jvm#13]
@SackCastellon Could you have a look at https://github.com/soc/directories-jvm/commit/dfba1eae53b89ef14529b06be3667ef957525c54 and test it on your system to make sure it returns all the results we expect?

I'm a bit concerned about the Linux change, as instead of running `xdg-user-dirs` directly, we are now running `bash` to execute multiple commands. I should probably benchmark this, to make sure we are actually faster...

**Comment by SackCastellon** [comment]
I tested it on _Windows 7_ and _Windows 10_, and it works as expected.
Currently, I am not able to test it on Linux to compare the performance.

**Comment by soc** [comment]
Thanks, I set up CI for Windows and it looks fine there too.

I think the current state should be fine for shipping, and I'll cut a new release in the evening as benchmarking the changes on Linux is not reliant on that. Even if I changed it back on Linux, it should not be visible to users of the library.

**Comment by soc** [comment]
It got pointed out to me that the code to access the directory information already exists in https://github.com/dotnet/corefx/blob/afcbd9a5b9e4ecde2db3a69afd093631f1db91c5/src/Common/src/Interop/Windows/shell32/Interop.SHGetKnownFolderPath.cs#L16.

Would it be easier/faster to just call that method?

**Comment by SackCastellon** [comment]
Maybe, but I am not that familiar with _.NET_ or _C#_ so I don't really know how to implement it.

**Comment by soc** [comment]
Don't worry, I more or less just added the comment to remind myself to look into it.
