### ISSUE TITLE
Use 'Java Native Access' (JNA) instead of PowerShell tricks?

### ISSUE THREAD

**Issue by SackCastellon** [soc/directories-jvm#16]
I just found [java-native-access/jna](https://github.com/java-native-access/jna) and I think instead of calling the PowerShell we could use [`Shell32Util.getKnownFolderPath(Guid.GUID guid)`](https://java-native-access.github.io/jna/4.2.1/com/sun/jna/platform/win32/Shell32Util.html#getKnownFolderPath-com.sun.jna.platform.win32.Guid.GUID-) together with [`KnownFolders`](https://java-native-access.github.io/jna/4.2.1/com/sun/jna/platform/win32/KnownFolders.html) to get the corresponding folder path.

For example:

```java
String desktopPath = Shell32Util.getKnownFolderPath(KnownFolders.FOLDERID_Desktop);
```

What do you think?

**Comment by soc** [comment]
Wouldn't this require shipping multiple DLLs inside the JAR file for whatever platform Windows runs on?

**Comment by SackCastellon** [comment]
- Yes
- Probably

**Comment by soc** [comment]
I'm closing this – my plan is to wait for Project Panama to enable first-class access to native code.
