### ISSUE TITLE
Issue with paths when username contains special characters on Windows

### ISSUE THREAD

**Issue by alexarchambault** [soc/directories-jvm#19]
Related to https://github.com/coursier/coursier/issues/904.

On Windows, if the user name contains a special character (e.g. `é`), the directories provided by `ProjectDirectories` seems right (`toString` prints chars that seem correct), but can't be passed to `java.io.File` (the corresponding file / directory doesn't exist). On the other hand, `sys.env("LOCALAPPDATA")` gives a path with an apparently wrong special character in `toString`… but `java.io.File` accepts it, and it actually correspond to the underlying file / directory.

See https://github.com/alexarchambault/directories-windows-special-char for a small repro. From Windows with a username having a special character, `sbt run` fails for me, like
```
[info] Compiling 1 Scala source to C:\Users\HalÞx\projects\coursier\foo\target\scala-2.12\classes ...
[info] Done compiling.
[info] Packaging C:\Users\HalÞx\projects\coursier\foo\target\scala-2.12\foo_2.12-0.1.0-SNAPSHOT.jar ...
[info] Done packaging.
[info] Running Check
dirNameViaDirectories=Halèx, isDirectory: false
dirNameViaLocalAppData=HalÞx, isDirectory: true
[error] (run-main-0) java.lang.AssertionError: assertion failed: Halèx != HalÞx
[error] java.lang.AssertionError: assertion failed: Halèx != HalÞx
[error]         at scala.Predef$.assert(Predef.scala:219)
[error]         at Check$.main(Check.scala:16)
[error]         at Check.main(Check.scala)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
[error] Nonzero exit code: 1
[error] (Compile / run) Nonzero exit code: 1
```

**Comment by alexarchambault** [comment]
FYI, I think I managed to find the issue… I'll submit a fix tomorrow I guess.

**Comment by soc** [comment]
Thanks!
