### ISSUE TITLE
Solaris is not supported

### ISSUE THREAD

**Issue by tomasjura** [soc/directories-jvm#23]
Solaris is not supported. 

Conseqently sbt 1.3.2 fails with a supprising error `lmcoursier.internal.shaded.coursier.cache.shaded.io.github.soc.directories.UnsupportedOperatingSystemException: directories are not supported on SunOS`

patch necessary (at least) on
io/github/soc/directories/Util.java:33
io/github/soc/directories/UserDirectories.java:305

**Comment by soc** [comment]
Hi @tomasjura I don't have a Solaris system, but if you would be able to provide a patch, I'd be happy to review and merge it.

**Comment by soc** [comment]
Heads up: I just published v12.
