### ISSUE TITLE
On Windows + AdoptOpenJDK 8 232-b09, ProjectDirectories.fromPath returns "null" directories

### ISSUE THREAD

**Issue by eed3si9n** [soc/directories-jvm#26]
This was originally reported as https://github.com/sbt/sbt/issues/5206 On Windows, Coursier creates "./null/Coursier/cache/v1" directories as cache and https://github.com/coursier/coursier/issues/1438

## steps

1. Use Windows.
2. Download the AdoptOpenJDK 8 232-b09 zip file (https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u232-b09/OpenJDK8U-jdk_x86-32_windows_hotspot_8u232b09.zip)
3. Launch sbt as follows:

```
sbt --java-home /cygdrive/c/Users/foo/Downloads/OpenJDK8U-jdk_x86-32_windows_hotspot_8u232b09/jdk8u232-b09/
```

4. add directories-jvm to libraryDependencies and call

```scala
scala> io.github.soc.directories.ProjectDirectories.fromPath("Coursier")
```

## problem

```
ProjectDirectories (Windows 7):
  projectPath  = 'Coursier'
  cacheDir     = 'null\Corusier\cache'
  configDir    = 'null\Corusier\config'
  dataDir      = 'null\Corusier\data'
  dataLocalDir = 'null\Corusier\data'
  runtimeDir   = 'null'
```

It points a relative path named `"null"`.

## expectation

https://github.com/soc/directories-jvm#projectdirectories

## notes

https://github.com/soc/directories-jvm/blob/8849872b9b71a378e6356f69bcf58427cb681e2f/src/main/java/io/github/soc/directories/Util.java#L113-L145

**Comment by soc** [comment]
@eed3si9n Thanks, I will look into this!

**Comment by eed3si9n** [comment]
Why not use the environment variable `LOCALAPPDATA`? It seems less scarier than shelling out to powershell.

**Comment by alexarchambault** [comment]
I've been wondering why we're not using the `LocalAppData` and `AppData` env vars too.

**Comment by eed3si9n** [comment]
Especially since sbt + Coursier doesn't need "Music" directory.

**Comment by alexarchambault** [comment]
The powershell stuff seems to be required for `UserDirectories`, possibly less so for `ProjectDirectories`, yes.

**Comment by soc** [comment]
@eed3si9n @alexarchambault There was a reason why I abandoned that approach, but I don't remember the reason anymore...

**Comment by eed3si9n** [comment]
If you're ok with JNA here's an implementation from a library that's doing similar things - https://github.com/harawata/appdirs/blob/master/src/main/java/net/harawata/appdirs/impl/ShellFolderResolver.java

**Comment by alexarchambault** [comment]
@eed3si9n See https://github.com/soc/directories-jvm/issues/16#issuecomment-382566836 for a discussion about JNA. AFAIC, I'm glab directories-jvm doesn't use it, so that it's more lightweight.

**Comment by alexarchambault** [comment]
I was able to reproduce the steps above on a Windows 10 machine. Something really weird though: I can't reproduce that error from Ammonite.

From sbt (getting nulls):
```
C:\Users\Alexandre\projects\test-directories>type project\build.properties
sbt.version=1.3.6

C:\Users\Alexandre\projects\test-directories>type build.sbt
libraryDependencies += "io.github.soc" % "directories" % "11"

C:\Users\Alexandre\projects\test-directories>sbt console
...
scala> io.github.soc.directories.ProjectDirectories.fromPath("Coursier")
res0: io.github.soc.directories.ProjectDirectories =
ProjectDirectories (Windows 10):
  projectPath  = 'Coursier'
  cacheDir     = 'null\Coursier\cache'
  configDir    = 'null\Coursier\config'
  dataDir      = 'null\Coursier\data'
  dataLocalDir = 'null\Coursier\data'
  runtimeDir   = 'null'
scala> :q
```

From Ammonite (almost no nulls):
```
C:\Users\Alexandre\projects\test-directories>coursier launch ammonite:2.0.1
...
@ import $ivy.`io.github.soc:directories:11`
@ io.github.soc.directories.ProjectDirectories.fromPath("Coursier")
res1: io.github.soc.directories.ProjectDirectories = ProjectDirectories (Windows 10):
  projectPath  = 'Coursier'
  cacheDir     = 'C:\Users\Alexandre\AppData\Local\Coursier\cache'
  configDir    = 'C:\Users\Alexandre\AppData\Roaming\Coursier\config'
  dataDir      = 'C:\Users\Alexandre\AppData\Roaming\Coursier\data'
  dataLocalDir = 'C:\Users\Alexandre\AppData\Local\Coursier\data'
  runtimeDir   = 'null'
@ sys.props("java.version") // check we're using the right JDK
res2: String = "1.8.0_232"
@ sys.props("java.home")
res3: String = "C:\\Users\\Alexandre\\.jabba\\jdk\\adopt@1.8.0-232\\jre
@ sys.props("java.vm.version")
res4: String = "25.232-b09"
```

**Comment by alexarchambault** [comment]
Same when loading lm-coursier-shaded from Ammonite (no nulls):
```
C:\> coursier launch ammonite:2.0.1
@ import $ivy.`io.get-coursier::lm-coursier-shaded:2.0.0-RC5-2`
@ val cls = Thread.currentThread.getContextClassLoader.loadClass("lmcoursier.internal.shaded.coursier.cache.
CacheDefaults$")
@ val defaults = cls.getFields.head.get(null)
@ val method = defaults.getClass.getMethod("location")
@ println(method.invoke(defaults))
C:\Users\Alexandre\AppData\Local\Coursier\cache\v1
```

**Comment by alexarchambault** [comment]
Could sbt somehow change things (in... the environment? something else?) that make powershell or the windows calls behave differently?

I tried printing the error stream of the powershell process too, and saw nothing suspicious there.

**Comment by alexarchambault** [comment]
Ok, that seems to originate from [these changes](https://www.oracle.com/technetwork/java/javase/8u231-relnotes-5592812.html#JDK-8221858).

Calling `System.setProperty("jdk.lang.Process.allowAmbiguousCommands", "true")` before the calls to directories-jvm seems to fix the issue \o/

**Comment by soc** [comment]
Seems to be a response to a CVE: https://bugzilla.redhat.com/show_bug.cgi?id=1777929

I can't find anything helpful on how to escape/rewrite the command though, because that would have been my first approach: The JDK doesn't like ambiguous commands anymore? Fine, I will change them to make them unambiguous.

**Comment by soc** [comment]
Nevertheless, I think there is also a bug in handling the `null`s – the user shouldn't receive a path if the operation to retrieve it has failed.

**Comment by szeiger** [comment]
> using paths with %LocalAppData% doesn't really work either, because you need something to resolve it.

What do you mean by something to resolve it?

**Comment by soc** [comment]
@szeiger You can't use %LocalAppData% in your file/path APIs expecting that it gets turned into a real path when it hits the Win32 API.

**Comment by szeiger** [comment]
I still don't see the problem. It's an environment variable. Use `System.getenv` to read it and you have an absolute path. Is there any situation where it would be something else?

**Comment by dwijnand** [comment]
@szeiger this comment https://stackoverflow.com/questions/1198911/how-to-get-local-application-data-folder-in-java#comment4791986_1198954:

> Note that the APPDATA environment variable is not available in applications that has been started via "Run As ..."

**Comment by soc** [comment]
I'd also be unsure whether the Win32 API takes a modified environment variable into account (and I think it's reasonable to consider the API the source of truth).

**Comment by soc** [comment]
Probably not: https://devblogs.microsoft.com/oldnewthing/20200115-00/?p=103329

Changing `Local_AppData` just got axed, it's likely that setting `%LocalAppData%` will have no effect, except setting `%LocalAppData%` to a place without a local app data folder.

**Comment by alexarchambault** [comment]
I found out that powershell accepts base64-encoded programs via [`-EncodedCommand`](https://docs.microsoft.com/fr-fr/powershell/module/Microsoft.PowerShell.Core/About/about_pwsh?view=powershell-7#-encodedcommand---e---ec), so that we don't have to fight with escaping like in https://github.com/soc/directories-jvm/pull/27.

It seems to work well (using it in another context [in coursier](https://github.com/coursier/coursier/blob/74ec8de1f653f553907c6ba3ca2d14f30dbeb1de/modules/env/src/main/scala/coursier/env/PowershellRunner.scala#L25-L27)).

**Comment by soc** [comment]
Heads up: I just published v12.

**Comment by philwalk** [comment]
The powershell command with -EncodedCommand still fails on my Windows 10 system, due to a missing .NET Framework:

```
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -version 2 -NoProfile -EncodedCommand blah-blah-blah

Version v2.0.50727 of the .NET Framework is not installed and it is required to run version 2 of Windows PowerShell.
```
I never use powershell.

A possible workaround is to set `COURSIER_JVM_CACHE=$COURSIER_CACHE`, but I'm not sure what the ramifications of that are.   It does hide the problem.

**Comment by soc** [comment]
@philwalk I don't think this related to this issue, I think this is https://github.com/dirs-dev/directories-jvm/issues/47.

**Comment by philwalk** [comment]
@soc ahh, thanks, sorry for the noise!

**Comment by soc** [comment]
no problem!
